# Generated by Django 2.0.6 on 2020-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201111_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscount',
            name='condition',
            field=models.IntegerField(blank=True, default=0, help_text='设置参与优惠的价格门槛，表示商品必须在xx价格以上的时候才参与优惠活动，<br>如果不填，则不设置门槛', verbose_name='满足优惠的价格条件'),
        ),
    ]
